/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardIndexRouteImport } from './routes/onboard/index'
import { Route as OIndexRouteImport } from './routes/o/index'
import { Route as OnboardInvitesRouteImport } from './routes/onboard/invites'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as indexApiKeysRouteImport } from './routes/(index)/api-keys'
import { Route as indexAuthedRouteImport } from './routes/(index)/_authed'
import { Route as OnboardUserIndexRouteImport } from './routes/onboard/user/index'
import { Route as OnboardOrgIndexRouteImport } from './routes/onboard/org/index'
import { Route as OOrgSlugAuthedRouteImport } from './routes/o.$orgSlug._authed'
import { Route as indexAuthedSettingsIndexRouteImport } from './routes/(index)/_authed.settings/index'
import { Route as OOrgSlugAuthedSettingsIndexRouteImport } from './routes/o.$orgSlug._authed/settings/index'
import { Route as OOrgSlugAuthedProjectsIndexRouteImport } from './routes/o.$orgSlug._authed/projects/index'
import { Route as OOrgSlugAuthedindexIndexRouteImport } from './routes/o.$orgSlug._authed/(index)/index'
import { Route as indexAuthedSettingsAccountIndexRouteImport } from './routes/(index)/_authed.settings/account/index'
import { Route as indexAuthedSettingsAccountPreferencesRouteImport } from './routes/(index)/_authed.settings/account/preferences'
import { Route as OOrgSlugAuthedSettingsOrgIndexRouteImport } from './routes/o.$orgSlug._authed/settings/org/index'
import { Route as OOrgSlugAuthedSettingsAccountIndexRouteImport } from './routes/o.$orgSlug._authed/settings/account/index'
import { Route as OOrgSlugAuthedSettingsOrgMembersRouteImport } from './routes/o.$orgSlug._authed/settings/org/members'
import { Route as OOrgSlugAuthedSettingsOrgDevelopersRouteImport } from './routes/o.$orgSlug._authed/settings/org/developers'
import { Route as OOrgSlugAuthedSettingsOrgBillingRouteImport } from './routes/o.$orgSlug._authed/settings/org/billing'
import { Route as OOrgSlugAuthedSettingsAccountPreferencesRouteImport } from './routes/o.$orgSlug._authed/settings/account/preferences'
import { Route as OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRouteImport } from './routes/o.$orgSlug._authed/(runComparison)/projects.$projectName/index'
import { Route as OOrgSlugAuthedrunComparisonProjectsProjectNameTableRouteImport } from './routes/o.$orgSlug._authed/(runComparison)/projects.$projectName/table'
import { Route as OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRouteImport } from './routes/o.$orgSlug._authed/(run)/projects.$projectName.$runId/index'
import { Route as OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRouteImport } from './routes/o.$orgSlug._authed/(run)/projects.$projectName.$runId/system'
import { Route as OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRouteImport } from './routes/o.$orgSlug._authed/(run)/projects.$projectName.$runId/logs'
import { Route as OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRouteImport } from './routes/o.$orgSlug._authed/(run)/projects.$projectName.$runId/graph'
import { Route as OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRouteImport } from './routes/o.$orgSlug._authed/(run)/projects.$projectName.$runId/summary/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardIndexRoute = OnboardIndexRouteImport.update({
  id: '/onboard/',
  path: '/onboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OIndexRoute = OIndexRouteImport.update({
  id: '/o/',
  path: '/o/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardInvitesRoute = OnboardInvitesRouteImport.update({
  id: '/onboard/invites',
  path: '/onboard/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const indexApiKeysRoute = indexApiKeysRouteImport.update({
  id: '/(index)/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const indexAuthedRoute = indexAuthedRouteImport.update({
  id: '/(index)/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardUserIndexRoute = OnboardUserIndexRouteImport.update({
  id: '/onboard/user/',
  path: '/onboard/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardOrgIndexRoute = OnboardOrgIndexRouteImport.update({
  id: '/onboard/org/',
  path: '/onboard/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugAuthedRoute = OOrgSlugAuthedRouteImport.update({
  id: '/o/$orgSlug/_authed',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const indexAuthedSettingsIndexRoute =
  indexAuthedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => indexAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsIndexRoute =
  OOrgSlugAuthedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedProjectsIndexRoute =
  OOrgSlugAuthedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedindexIndexRoute =
  OOrgSlugAuthedindexIndexRouteImport.update({
    id: '/(index)/',
    path: '/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const indexAuthedSettingsAccountIndexRoute =
  indexAuthedSettingsAccountIndexRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => indexAuthedRoute,
  } as any)
const indexAuthedSettingsAccountPreferencesRoute =
  indexAuthedSettingsAccountPreferencesRouteImport.update({
    id: '/settings/account/preferences',
    path: '/settings/account/preferences',
    getParentRoute: () => indexAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsOrgIndexRoute =
  OOrgSlugAuthedSettingsOrgIndexRouteImport.update({
    id: '/settings/org/',
    path: '/settings/org/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsAccountIndexRoute =
  OOrgSlugAuthedSettingsAccountIndexRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsOrgMembersRoute =
  OOrgSlugAuthedSettingsOrgMembersRouteImport.update({
    id: '/settings/org/members',
    path: '/settings/org/members',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsOrgDevelopersRoute =
  OOrgSlugAuthedSettingsOrgDevelopersRouteImport.update({
    id: '/settings/org/developers',
    path: '/settings/org/developers',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsOrgBillingRoute =
  OOrgSlugAuthedSettingsOrgBillingRouteImport.update({
    id: '/settings/org/billing',
    path: '/settings/org/billing',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedSettingsAccountPreferencesRoute =
  OOrgSlugAuthedSettingsAccountPreferencesRouteImport.update({
    id: '/settings/account/preferences',
    path: '/settings/account/preferences',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute =
  OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRouteImport.update({
    id: '/(runComparison)/projects/$projectName/',
    path: '/projects/$projectName/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute =
  OOrgSlugAuthedrunComparisonProjectsProjectNameTableRouteImport.update({
    id: '/(runComparison)/projects/$projectName/table',
    path: '/projects/$projectName/table',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute =
  OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRouteImport.update({
    id: '/(run)/projects/$projectName/$runId/',
    path: '/projects/$projectName/$runId/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute =
  OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRouteImport.update({
    id: '/(run)/projects/$projectName/$runId/system',
    path: '/projects/$projectName/$runId/system',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute =
  OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRouteImport.update({
    id: '/(run)/projects/$projectName/$runId/logs',
    path: '/projects/$projectName/$runId/logs',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute =
  OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRouteImport.update({
    id: '/(run)/projects/$projectName/$runId/graph',
    path: '/projects/$projectName/$runId/graph',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)
const OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute =
  OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRouteImport.update({
    id: '/(run)/projects/$projectName/$runId/summary/',
    path: '/projects/$projectName/$runId/summary/',
    getParentRoute: () => OOrgSlugAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof indexApiKeysRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboard/invites': typeof OnboardInvitesRoute
  '/o/': typeof OIndexRoute
  '/onboard/': typeof OnboardIndexRoute
  '/o/$orgSlug': typeof OOrgSlugAuthedRouteWithChildren
  '/onboard/org/': typeof OnboardOrgIndexRoute
  '/onboard/user/': typeof OnboardUserIndexRoute
  '/settings/': typeof indexAuthedSettingsIndexRoute
  '/settings/account/preferences': typeof indexAuthedSettingsAccountPreferencesRoute
  '/settings/account/': typeof indexAuthedSettingsAccountIndexRoute
  '/o/$orgSlug/': typeof OOrgSlugAuthedindexIndexRoute
  '/o/$orgSlug/projects/': typeof OOrgSlugAuthedProjectsIndexRoute
  '/o/$orgSlug/settings/': typeof OOrgSlugAuthedSettingsIndexRoute
  '/o/$orgSlug/settings/account/preferences': typeof OOrgSlugAuthedSettingsAccountPreferencesRoute
  '/o/$orgSlug/settings/org/billing': typeof OOrgSlugAuthedSettingsOrgBillingRoute
  '/o/$orgSlug/settings/org/developers': typeof OOrgSlugAuthedSettingsOrgDevelopersRoute
  '/o/$orgSlug/settings/org/members': typeof OOrgSlugAuthedSettingsOrgMembersRoute
  '/o/$orgSlug/settings/account/': typeof OOrgSlugAuthedSettingsAccountIndexRoute
  '/o/$orgSlug/settings/org/': typeof OOrgSlugAuthedSettingsOrgIndexRoute
  '/o/$orgSlug/projects/$projectName/table': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute
  '/o/$orgSlug/projects/$projectName/': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute
  '/o/$orgSlug/projects/$projectName/$runId/graph': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute
  '/o/$orgSlug/projects/$projectName/$runId/logs': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute
  '/o/$orgSlug/projects/$projectName/$runId/system': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute
  '/o/$orgSlug/projects/$projectName/$runId/': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute
  '/o/$orgSlug/projects/$projectName/$runId/summary/': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof indexApiKeysRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboard/invites': typeof OnboardInvitesRoute
  '/o': typeof OIndexRoute
  '/onboard': typeof OnboardIndexRoute
  '/onboard/org': typeof OnboardOrgIndexRoute
  '/onboard/user': typeof OnboardUserIndexRoute
  '/settings': typeof indexAuthedSettingsIndexRoute
  '/settings/account/preferences': typeof indexAuthedSettingsAccountPreferencesRoute
  '/settings/account': typeof indexAuthedSettingsAccountIndexRoute
  '/o/$orgSlug': typeof OOrgSlugAuthedindexIndexRoute
  '/o/$orgSlug/projects': typeof OOrgSlugAuthedProjectsIndexRoute
  '/o/$orgSlug/settings': typeof OOrgSlugAuthedSettingsIndexRoute
  '/o/$orgSlug/settings/account/preferences': typeof OOrgSlugAuthedSettingsAccountPreferencesRoute
  '/o/$orgSlug/settings/org/billing': typeof OOrgSlugAuthedSettingsOrgBillingRoute
  '/o/$orgSlug/settings/org/developers': typeof OOrgSlugAuthedSettingsOrgDevelopersRoute
  '/o/$orgSlug/settings/org/members': typeof OOrgSlugAuthedSettingsOrgMembersRoute
  '/o/$orgSlug/settings/account': typeof OOrgSlugAuthedSettingsAccountIndexRoute
  '/o/$orgSlug/settings/org': typeof OOrgSlugAuthedSettingsOrgIndexRoute
  '/o/$orgSlug/projects/$projectName/table': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute
  '/o/$orgSlug/projects/$projectName': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute
  '/o/$orgSlug/projects/$projectName/$runId/graph': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute
  '/o/$orgSlug/projects/$projectName/$runId/logs': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute
  '/o/$orgSlug/projects/$projectName/$runId/system': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute
  '/o/$orgSlug/projects/$projectName/$runId': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute
  '/o/$orgSlug/projects/$projectName/$runId/summary': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(index)/_authed': typeof indexAuthedRouteWithChildren
  '/(index)/api-keys': typeof indexApiKeysRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboard/invites': typeof OnboardInvitesRoute
  '/o/': typeof OIndexRoute
  '/onboard/': typeof OnboardIndexRoute
  '/o/$orgSlug/_authed': typeof OOrgSlugAuthedRouteWithChildren
  '/onboard/org/': typeof OnboardOrgIndexRoute
  '/onboard/user/': typeof OnboardUserIndexRoute
  '/(index)/_authed/settings/': typeof indexAuthedSettingsIndexRoute
  '/(index)/_authed/settings/account/preferences': typeof indexAuthedSettingsAccountPreferencesRoute
  '/(index)/_authed/settings/account/': typeof indexAuthedSettingsAccountIndexRoute
  '/o/$orgSlug/_authed/(index)/': typeof OOrgSlugAuthedindexIndexRoute
  '/o/$orgSlug/_authed/projects/': typeof OOrgSlugAuthedProjectsIndexRoute
  '/o/$orgSlug/_authed/settings/': typeof OOrgSlugAuthedSettingsIndexRoute
  '/o/$orgSlug/_authed/settings/account/preferences': typeof OOrgSlugAuthedSettingsAccountPreferencesRoute
  '/o/$orgSlug/_authed/settings/org/billing': typeof OOrgSlugAuthedSettingsOrgBillingRoute
  '/o/$orgSlug/_authed/settings/org/developers': typeof OOrgSlugAuthedSettingsOrgDevelopersRoute
  '/o/$orgSlug/_authed/settings/org/members': typeof OOrgSlugAuthedSettingsOrgMembersRoute
  '/o/$orgSlug/_authed/settings/account/': typeof OOrgSlugAuthedSettingsAccountIndexRoute
  '/o/$orgSlug/_authed/settings/org/': typeof OOrgSlugAuthedSettingsOrgIndexRoute
  '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/table': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute
  '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/': typeof OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute
  '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/graph': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute
  '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/logs': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute
  '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/system': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute
  '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute
  '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/summary/': typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/onboard/invites'
    | '/o/'
    | '/onboard/'
    | '/o/$orgSlug'
    | '/onboard/org/'
    | '/onboard/user/'
    | '/settings/'
    | '/settings/account/preferences'
    | '/settings/account/'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/projects/'
    | '/o/$orgSlug/settings/'
    | '/o/$orgSlug/settings/account/preferences'
    | '/o/$orgSlug/settings/org/billing'
    | '/o/$orgSlug/settings/org/developers'
    | '/o/$orgSlug/settings/org/members'
    | '/o/$orgSlug/settings/account/'
    | '/o/$orgSlug/settings/org/'
    | '/o/$orgSlug/projects/$projectName/table'
    | '/o/$orgSlug/projects/$projectName/'
    | '/o/$orgSlug/projects/$projectName/$runId/graph'
    | '/o/$orgSlug/projects/$projectName/$runId/logs'
    | '/o/$orgSlug/projects/$projectName/$runId/system'
    | '/o/$orgSlug/projects/$projectName/$runId/'
    | '/o/$orgSlug/projects/$projectName/$runId/summary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/onboard/invites'
    | '/o'
    | '/onboard'
    | '/onboard/org'
    | '/onboard/user'
    | '/settings'
    | '/settings/account/preferences'
    | '/settings/account'
    | '/o/$orgSlug'
    | '/o/$orgSlug/projects'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/settings/account/preferences'
    | '/o/$orgSlug/settings/org/billing'
    | '/o/$orgSlug/settings/org/developers'
    | '/o/$orgSlug/settings/org/members'
    | '/o/$orgSlug/settings/account'
    | '/o/$orgSlug/settings/org'
    | '/o/$orgSlug/projects/$projectName/table'
    | '/o/$orgSlug/projects/$projectName'
    | '/o/$orgSlug/projects/$projectName/$runId/graph'
    | '/o/$orgSlug/projects/$projectName/$runId/logs'
    | '/o/$orgSlug/projects/$projectName/$runId/system'
    | '/o/$orgSlug/projects/$projectName/$runId'
    | '/o/$orgSlug/projects/$projectName/$runId/summary'
  id:
    | '__root__'
    | '/'
    | '/(index)/_authed'
    | '/(index)/api-keys'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/onboard/invites'
    | '/o/'
    | '/onboard/'
    | '/o/$orgSlug/_authed'
    | '/onboard/org/'
    | '/onboard/user/'
    | '/(index)/_authed/settings/'
    | '/(index)/_authed/settings/account/preferences'
    | '/(index)/_authed/settings/account/'
    | '/o/$orgSlug/_authed/(index)/'
    | '/o/$orgSlug/_authed/projects/'
    | '/o/$orgSlug/_authed/settings/'
    | '/o/$orgSlug/_authed/settings/account/preferences'
    | '/o/$orgSlug/_authed/settings/org/billing'
    | '/o/$orgSlug/_authed/settings/org/developers'
    | '/o/$orgSlug/_authed/settings/org/members'
    | '/o/$orgSlug/_authed/settings/account/'
    | '/o/$orgSlug/_authed/settings/org/'
    | '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/table'
    | '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/'
    | '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/graph'
    | '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/logs'
    | '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/system'
    | '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/'
    | '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/summary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  indexAuthedRoute: typeof indexAuthedRouteWithChildren
  indexApiKeysRoute: typeof indexApiKeysRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  OnboardInvitesRoute: typeof OnboardInvitesRoute
  OIndexRoute: typeof OIndexRoute
  OnboardIndexRoute: typeof OnboardIndexRoute
  OOrgSlugAuthedRoute: typeof OOrgSlugAuthedRouteWithChildren
  OnboardOrgIndexRoute: typeof OnboardOrgIndexRoute
  OnboardUserIndexRoute: typeof OnboardUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/': {
      id: '/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof OnboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/': {
      id: '/o/'
      path: '/o'
      fullPath: '/o/'
      preLoaderRoute: typeof OIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/invites': {
      id: '/onboard/invites'
      path: '/onboard/invites'
      fullPath: '/onboard/invites'
      preLoaderRoute: typeof OnboardInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/api-keys': {
      id: '/(index)/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof indexApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/_authed': {
      id: '/(index)/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof indexAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/user/': {
      id: '/onboard/user/'
      path: '/onboard/user'
      fullPath: '/onboard/user/'
      preLoaderRoute: typeof OnboardUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/org/': {
      id: '/onboard/org/'
      path: '/onboard/org'
      fullPath: '/onboard/org/'
      preLoaderRoute: typeof OnboardOrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/_authed': {
      id: '/o/$orgSlug/_authed'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/_authed/settings/': {
      id: '/(index)/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof indexAuthedSettingsIndexRouteImport
      parentRoute: typeof indexAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/': {
      id: '/o/$orgSlug/_authed/settings/'
      path: '/settings'
      fullPath: '/o/$orgSlug/settings/'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/projects/': {
      id: '/o/$orgSlug/_authed/projects/'
      path: '/projects'
      fullPath: '/o/$orgSlug/projects/'
      preLoaderRoute: typeof OOrgSlugAuthedProjectsIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(index)/': {
      id: '/o/$orgSlug/_authed/(index)/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugAuthedindexIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/(index)/_authed/settings/account/': {
      id: '/(index)/_authed/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof indexAuthedSettingsAccountIndexRouteImport
      parentRoute: typeof indexAuthedRoute
    }
    '/(index)/_authed/settings/account/preferences': {
      id: '/(index)/_authed/settings/account/preferences'
      path: '/settings/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof indexAuthedSettingsAccountPreferencesRouteImport
      parentRoute: typeof indexAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/org/': {
      id: '/o/$orgSlug/_authed/settings/org/'
      path: '/settings/org'
      fullPath: '/o/$orgSlug/settings/org/'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsOrgIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/account/': {
      id: '/o/$orgSlug/_authed/settings/account/'
      path: '/settings/account'
      fullPath: '/o/$orgSlug/settings/account/'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsAccountIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/org/members': {
      id: '/o/$orgSlug/_authed/settings/org/members'
      path: '/settings/org/members'
      fullPath: '/o/$orgSlug/settings/org/members'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsOrgMembersRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/org/developers': {
      id: '/o/$orgSlug/_authed/settings/org/developers'
      path: '/settings/org/developers'
      fullPath: '/o/$orgSlug/settings/org/developers'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsOrgDevelopersRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/org/billing': {
      id: '/o/$orgSlug/_authed/settings/org/billing'
      path: '/settings/org/billing'
      fullPath: '/o/$orgSlug/settings/org/billing'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsOrgBillingRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/settings/account/preferences': {
      id: '/o/$orgSlug/_authed/settings/account/preferences'
      path: '/settings/account/preferences'
      fullPath: '/o/$orgSlug/settings/account/preferences'
      preLoaderRoute: typeof OOrgSlugAuthedSettingsAccountPreferencesRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/': {
      id: '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/'
      path: '/projects/$projectName'
      fullPath: '/o/$orgSlug/projects/$projectName/'
      preLoaderRoute: typeof OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/table': {
      id: '/o/$orgSlug/_authed/(runComparison)/projects/$projectName/table'
      path: '/projects/$projectName/table'
      fullPath: '/o/$orgSlug/projects/$projectName/table'
      preLoaderRoute: typeof OOrgSlugAuthedrunComparisonProjectsProjectNameTableRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/': {
      id: '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/'
      path: '/projects/$projectName/$runId'
      fullPath: '/o/$orgSlug/projects/$projectName/$runId/'
      preLoaderRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/system': {
      id: '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/system'
      path: '/projects/$projectName/$runId/system'
      fullPath: '/o/$orgSlug/projects/$projectName/$runId/system'
      preLoaderRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/logs': {
      id: '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/logs'
      path: '/projects/$projectName/$runId/logs'
      fullPath: '/o/$orgSlug/projects/$projectName/$runId/logs'
      preLoaderRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/graph': {
      id: '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/graph'
      path: '/projects/$projectName/$runId/graph'
      fullPath: '/o/$orgSlug/projects/$projectName/$runId/graph'
      preLoaderRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
    '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/summary/': {
      id: '/o/$orgSlug/_authed/(run)/projects/$projectName/$runId/summary/'
      path: '/projects/$projectName/$runId/summary'
      fullPath: '/o/$orgSlug/projects/$projectName/$runId/summary/'
      preLoaderRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRouteImport
      parentRoute: typeof OOrgSlugAuthedRoute
    }
  }
}

interface indexAuthedRouteChildren {
  indexAuthedSettingsIndexRoute: typeof indexAuthedSettingsIndexRoute
  indexAuthedSettingsAccountPreferencesRoute: typeof indexAuthedSettingsAccountPreferencesRoute
  indexAuthedSettingsAccountIndexRoute: typeof indexAuthedSettingsAccountIndexRoute
}

const indexAuthedRouteChildren: indexAuthedRouteChildren = {
  indexAuthedSettingsIndexRoute: indexAuthedSettingsIndexRoute,
  indexAuthedSettingsAccountPreferencesRoute:
    indexAuthedSettingsAccountPreferencesRoute,
  indexAuthedSettingsAccountIndexRoute: indexAuthedSettingsAccountIndexRoute,
}

const indexAuthedRouteWithChildren = indexAuthedRoute._addFileChildren(
  indexAuthedRouteChildren,
)

interface OOrgSlugAuthedRouteChildren {
  OOrgSlugAuthedindexIndexRoute: typeof OOrgSlugAuthedindexIndexRoute
  OOrgSlugAuthedProjectsIndexRoute: typeof OOrgSlugAuthedProjectsIndexRoute
  OOrgSlugAuthedSettingsIndexRoute: typeof OOrgSlugAuthedSettingsIndexRoute
  OOrgSlugAuthedSettingsAccountPreferencesRoute: typeof OOrgSlugAuthedSettingsAccountPreferencesRoute
  OOrgSlugAuthedSettingsOrgBillingRoute: typeof OOrgSlugAuthedSettingsOrgBillingRoute
  OOrgSlugAuthedSettingsOrgDevelopersRoute: typeof OOrgSlugAuthedSettingsOrgDevelopersRoute
  OOrgSlugAuthedSettingsOrgMembersRoute: typeof OOrgSlugAuthedSettingsOrgMembersRoute
  OOrgSlugAuthedSettingsAccountIndexRoute: typeof OOrgSlugAuthedSettingsAccountIndexRoute
  OOrgSlugAuthedSettingsOrgIndexRoute: typeof OOrgSlugAuthedSettingsOrgIndexRoute
  OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute: typeof OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute
  OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute: typeof OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute
  OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute
  OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute
  OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute
  OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute
  OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute: typeof OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute
}

const OOrgSlugAuthedRouteChildren: OOrgSlugAuthedRouteChildren = {
  OOrgSlugAuthedindexIndexRoute: OOrgSlugAuthedindexIndexRoute,
  OOrgSlugAuthedProjectsIndexRoute: OOrgSlugAuthedProjectsIndexRoute,
  OOrgSlugAuthedSettingsIndexRoute: OOrgSlugAuthedSettingsIndexRoute,
  OOrgSlugAuthedSettingsAccountPreferencesRoute:
    OOrgSlugAuthedSettingsAccountPreferencesRoute,
  OOrgSlugAuthedSettingsOrgBillingRoute: OOrgSlugAuthedSettingsOrgBillingRoute,
  OOrgSlugAuthedSettingsOrgDevelopersRoute:
    OOrgSlugAuthedSettingsOrgDevelopersRoute,
  OOrgSlugAuthedSettingsOrgMembersRoute: OOrgSlugAuthedSettingsOrgMembersRoute,
  OOrgSlugAuthedSettingsAccountIndexRoute:
    OOrgSlugAuthedSettingsAccountIndexRoute,
  OOrgSlugAuthedSettingsOrgIndexRoute: OOrgSlugAuthedSettingsOrgIndexRoute,
  OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute:
    OOrgSlugAuthedrunComparisonProjectsProjectNameTableRoute,
  OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute:
    OOrgSlugAuthedrunComparisonProjectsProjectNameIndexRoute,
  OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute:
    OOrgSlugAuthedrunProjectsProjectNameRunIdGraphRoute,
  OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute:
    OOrgSlugAuthedrunProjectsProjectNameRunIdLogsRoute,
  OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute:
    OOrgSlugAuthedrunProjectsProjectNameRunIdSystemRoute,
  OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute:
    OOrgSlugAuthedrunProjectsProjectNameRunIdIndexRoute,
  OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute:
    OOrgSlugAuthedrunProjectsProjectNameRunIdSummaryIndexRoute,
}

const OOrgSlugAuthedRouteWithChildren = OOrgSlugAuthedRoute._addFileChildren(
  OOrgSlugAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  indexAuthedRoute: indexAuthedRouteWithChildren,
  indexApiKeysRoute: indexApiKeysRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  OnboardInvitesRoute: OnboardInvitesRoute,
  OIndexRoute: OIndexRoute,
  OnboardIndexRoute: OnboardIndexRoute,
  OOrgSlugAuthedRoute: OOrgSlugAuthedRouteWithChildren,
  OnboardOrgIndexRoute: OnboardOrgIndexRoute,
  OnboardUserIndexRoute: OnboardUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
